### ISSUE TITLE
UnicodeDecodeError when write the namegraph to dot format

### ISSUE THREAD

**Issue by litaotju** [litaotju/netlist_util#19]
Traceback (most recent call last):
  File "C:\Users\litao\Desktop\a.py", line 8, in <module>
    nx.write_dot(g, "abc.dot")
  File "<string>", line 2, in write_dot
  File "C:\Python27\lib\site-packages\networkx\utils\decorators.py", line 220, in _open_file
    result = func(_new_args, *_kwargs)
  File "C:\Python27\lib\site-packages\networkx\drawing\nx_pydot.py", line 58, in write_dot
    P=to_pydot(G)
  File "C:\Python27\lib\site-packages\networkx\drawing\nx_pydot.py", line 212, in to_pydot
    p=pydot.Node(make_str(n),**str_nodedata)
  File "C:\Python27\lib\site-packages\networkx\utils\misc.py", line 103, in make_str
    return unicode(str(x), 'unicode-escape')
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 0-1: truncated \UXXXXXXXX escape

**Comment by litaotju** [comment]
The problem can be bring back in again using the the code below

```
    import os
    import networkx as nx
    g = nx.DiGraph()
    g.add_node("\Unihdaas")
    nx.write_dot(g, "abc.dot")
```

In Python, a string-literal containing \U is an escape sequence which
expects exactly 8 hexadecimal digits to follow:
If you don't follow the \U with eight hex digits, you get an error:

So the when the node name has a "\U"  substring, will introduce an error using write_dot.
